
name: test-servant-py2
run-name: $${{ github.actor }} is testing servant with python2.7

on:
  pull_request:
    types: [opened, edited, reopened]
    paths:
      - '**'

jobs:
  run-servant-test-py2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test-servant-py2-step
      run: bash test-servant-py2.sh

